server:
  port: 8303

spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql的驱动你可以配置别的关系型数据库
    url: jdbc:mysql://127.0.0.1:3306/revitPlugin?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false&useUnicode=true #数据源地址
    username: root # 用户名
    password: root # 密码

redis:
  host: 127.0.0.1
  port: 6379
  timeout: 3600
  password:
  database: 0
  pool:
    maxTotal: 1000
    maxIdle: 100
    maxWaitMillis: 100000
    minIdle: 80


